#!/bin/bash

if [ "$USER" != "root" ]; then
	sudo ./install
	exit
fi

echo "Preparing to install"
echo "Searching for required depends..."

zipexists=0
gitexists=0
jqexists=0

for file in $(ls /bin); do
	if [ "$file" == "zip" ]; then zipexists=1
	elif [ "$file" == "git" ]; then gitexists=1
	elif [ "$file" == "jq" ]; then jqexists=1
	fi
done

if [ "$zipexists" == "1" ] && [ "$gitexists" == "1" ] && [ "$jqexists" == "1" ]; then
	echo "Ready to install"
	cp xlpm /bin
	xlpm --init
	echo "Successfully installed XLPM"
else
	echo -n "Some depends aren't installed. Do you want to install them? [y/n]"; read answer
	if [ "$answer" == "y" ]; then
		apt install zip git jq
		echo "Try to run this script again"
	fi
fi