#!/bin/bash
if [ "$USER" != "root" ]; then
	sudo ./remove
	exit
fi

echo -n "Are you sure want to remove xlpm? [y/n]"; read answer
if [ "$answer" == "y" ]; then
	rm /bin/xlpm
	echo "Do you want to remove XLPM config?"
	echo "After this operation you won't can remove packages which"
	echo -n "was installed with XLPM. Continue? [y/n]"; read answer
	if [ "$answer" == "y" ]; then
		rm -rf /etc/xlpm
	fi
	echo "XLPM was removed successfully"
fi
